module.exports = {
  "ALIVE_IMG": "https://raw.githubusercontent.com/RASH-DATA/ANJU-DATA/refs/heads/main/WhatsApp%20Image%202024-09-08%20at%209.00.17%20PM.jpeg",
  "PREFIX": ",",
  "AUTO_READ_STATUS": true,
  "MODE": "private",
  "BOT_NUMBER": "923295112243",
  "OMDB_API_KEY": "76cb7f39",
  "READ_CMD": true,
  "AUTO_VOICE": false,
  "AUTO_STICKER": false,
  "AUTO_REPLY": false,
  "AUTO_REACT": false,
  "WELCOME": false,
  "ANTI_BAD": false,
  "ANTI_BOT": false,
  "ANTI_LINK": false,
  "ANTI_CALL": false,
  "ANTI_DELETE": true,
  "ALLWAYS_ONLINE": true,
  "MOROCCO_BLOCK": false,
  "BTN_MSG": false,
  "OWNER_NAME": "MR Raju",
  "NEWS_JID": "1234567890@s.whatsapp.net",
  "AUTO_TYPING": false,
  "AUTO_RECORDING": false,
  "AUTO_NEWS": false,
  "OWNER_REACT": false,
  "EMOJI": "🏷",
  "AI_MODE": false
};
